### ISSUE TITLE
How to make my image fit the window size

### ISSUE THREAD

**Issue by Juliebou** [Juliebou/type-those-grids#1]
@hellachella
@carolsinc

My first image is very big on the screen. I don't know how to make it smaller and responsive to the size of my browser.

thanks, 
Julie B.

**Comment by Juliebou** [comment]
@carolsinc

My first image is very big on the screen. I don't know how to make it smaller and responsive to the size of my browser.

thanks,
Julie B.

**Comment by carolsinc** [comment]
set your image width to 100%
